# Generated by Django 3.0 on 2020-06-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'chair'), ('vice-chair', 'vice-chair'), ('collaborator', 'collaborator'), ('treasurer', 'treasurer'), ('secretary', 'secretary'), ('coordinator', 'coordinator'), ('innovation-manager', 'innovation-manager')], max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MemberModel')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatableContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField()),
                ('content_pt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_year', models.CharField(max_length=5)),
                ('members_ids', models.ManyToManyField(related_name='team_members', through='app.TeamMemberModel', to='app.MemberModel')),
            ],
        ),
        migrations.AddField(
            model_name='teammembermodel',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TeamModel'),
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('type', models.CharField(choices=[('members', 'members'), ('events', 'events'), ('repository', 'repository')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_name', to='app.TranslatableContentModel')),
            ],
        ),
        migrations.AddField(
            model_name='membermodel',
            name='description_ids',
            field=models.ManyToManyField(blank=True, to='app.TranslatableContentModel'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ImageModel'),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('description_ids', models.ManyToManyField(blank=True, related_name='event_description', to='app.TranslatableContentModel')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ImageModel')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TranslatableContentModel')),
                ('teams_ids', models.ManyToManyField(blank=True, related_name='department_teams', to='app.TeamModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('tag', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('departments_ids', models.ManyToManyField(blank=True, to='app.DepartmentModel')),
                ('description_ids', models.ManyToManyField(blank=True, to='app.TranslatableContentModel')),
                ('events_ids', models.ManyToManyField(blank=True, to='app.EventModel')),
                ('images_ids', models.ManyToManyField(blank=True, to='app.ImageModel')),
                ('pages_types_ids', models.ManyToManyField(blank=True, to='app.PageModel')),
            ],
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('departments_ids', models.ManyToManyField(blank=True, related_name='branch_departments', to='app.DepartmentModel')),
                ('description_ids', models.ManyToManyField(blank=True, related_name='branch_description', to='app.TranslatableContentModel')),
                ('events_ids', models.ManyToManyField(blank=True, related_name='branch_events', to='app.EventModel')),
                ('images_ids', models.ManyToManyField(blank=True, related_name='branch_images', to='app.ImageModel')),
                ('pages_types_ids', models.ManyToManyField(blank=True, related_name='branch_pages', to='app.PageModel')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year_edition', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=80)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ImageModel')),
                ('quality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TranslatableContentModel')),
            ],
        ),
    ]
