# Generated by Django 3.0 on 2020-02-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app/api/db/imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatableContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField()),
                ('content_pt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_year', models.CharField(max_length=5)),
                ('members', models.ManyToManyField(to='app.MemberModel')),
            ],
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('name', models.ManyToManyField(to='app.TranslatableContentModel')),
            ],
        ),
        migrations.AddField(
            model_name='membermodel',
            name='description',
            field=models.ManyToManyField(blank=True, to='app.TranslatableContentModel'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ImageModel'),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.ManyToManyField(blank=True, to='app.TranslatableContentModel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ImageModel')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(blank=True, to='app.TeamModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(max_length=8, unique=True)),
                ('departments', models.ManyToManyField(blank=True, to='app.DepartmentModel')),
                ('events', models.ManyToManyField(blank=True, to='app.EventModel')),
                ('images', models.ManyToManyField(blank=True, to='app.ImageModel')),
                ('pages', models.ManyToManyField(blank=True, to='app.PageModel')),
            ],
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(max_length=8, unique=True)),
                ('departments', models.ManyToManyField(blank=True, to='app.DepartmentModel')),
                ('description', models.ManyToManyField(blank=True, to='app.TranslatableContentModel')),
                ('events', models.ManyToManyField(blank=True, to='app.EventModel')),
                ('images', models.ManyToManyField(blank=True, to='app.ImageModel')),
                ('pages', models.ManyToManyField(blank=True, to='app.PageModel')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('year_edition', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('quality', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=80)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ImageModel')),
            ],
        ),
    ]
